#SETUP PYGAME ZERO
import pgzrun
#SCREEN
WIDTH = 100
HEIGHT = 100
#SETUP SCORE
#SETUP BRICK
#SETUP WALLS
#BUTTON PRESSES
#DRAW STUFF TO SCREEN
#EACH CYCLE THROUGH THE LOOP
#COLLISIONS
#RESET
#RUN PYGAME ZERO
pgzrun.go()